### ISSUE TITLE
E57 element path well formed but not defined (ErrorPathUndefined)

### ISSUE THREAD

**Issue by spro1976** [davidcaron/pye57#58]
I had the error 
`  
File ".venv\lib\site-packages\pye57\e57.py", line 214, in read_scan
    xyz = self.to_global(xyz, header.rotation, header.translation)
  File ".venv\lib\site-packages\pye57\scan_header.py", line 32, in rotation
    q = Quaternion([e.value() for e in self.node["pose"]["rotation"]])
pye57.libe57.E57Exception: E57 element path well formed but not defined (ErrorPathUndefined)
`
for e57 files created from Recap and also the [downloaded e57 sample file Trimble Data - Muliple Scans point cloud](http://sourceforge.net/projects/e57-3d-imgfmt/files/E57Example-data/Trimble_StSulpice-Cloud-50mm.e57/download) from [libe57](http://www.libe57.org/data.html)
Does anybody know this topic?

**Comment by dancergraham** [comment]
Hello,
Thanks for the sample file - that should help with debugging. I'm on holiday right now but I can have a look in a week or two if no-one has had the opportunity sooner

**Comment by Eecornwell** [comment]
I have had a similar error attempting to re-apply a previous header onto a new scan write. Any followup on what this error means?

**Comment by Eecornwell** [comment]
I was able to solve my issue by commenting out header attributes inside of `e57.py` (lines starting at 234) that are not currently in my scan headers. I believe temperature, humidity, and datetime was not in my original header that I was attempting to copy over.

**Comment by meLordlp** [comment]
Hi, I have the same issue. I solved it with changing the code locally.
In the `scan_header.py` in line 31 you should check if `rotation` is in `self.node["pose"]`. If not just return `Quaternion([1, 0, 0, 0]).elements`.
Can this be fixed?

**Comment by Napam** [comment]
I am also experiencing the same issue related to the scan_header. The error I get the following:

```
---------------------------------------------------------------------------
E57Exception                              Traceback (most recent call last)
Cell In[3], line 2
      1 e57_handle = pye57.E57("data/Tunnel nygårdsviken.e57")
----> 2 e57_data = e57_handle.read_scan(0, ignore_missing_fields=True)

File ~/work/projects/wg-scan/.venv/lib/python3.12/site-packages/pye57/e57.py:214, in E57.read_scan(self, index, intensity, colors, row_column, transform, ignore_missing_fields)
    212 # translation to global coordinates
    213 if header.has_pose():
--> 214     xyz = self.to_global(xyz, header.rotation, header.translation)
    215 data["cartesianX"] = xyz[:, 0]
    216 data["cartesianY"] = xyz[:, 1]

File ~/work/projects/wg-scan/.venv/lib/python3.12/site-packages/pye57/scan_header.py:37, in ScanHeader.rotation(self)
     34 @property
     35 def rotation(self) -> np.array:
     36     try:
---> 37         rotation = self.node["pose"]["rotation"]
     38         q = Quaternion([e.value() for e in rotation])
     39     except KeyError:

E57Exception: E57 element path well formed but not defined (ErrorPathUndefined)

**** Got an e57 exception: E57 element path well formed but not defined (ErrorPathUndefined)
  Debug info: 
    context: this->pathName=/data3D/0/pose pathName=rotation
    sourceFunctionName: get
    reportingFunctionName: operator()
/Users/runner/work/pye57/pye57/libE57Format/src/StructureNodeImpl.cpp(145) : error C22:  <--- occurred on
src/pye57/libe57_wrapper.cpp(49) : error C0:  <--- reported on
```

I did a very dirty quickfix by simply altering the error handling code in ScanHeader.rotation from this:
```python
    @property
    def rotation(self) -> np.array:
        try:
            rotation = self.node["pose"]["rotation"]
            q = Quaternion([e.value() for e in rotation])
        except KeyError:
            q = Quaternion()
        return q.elements
```
to this:
```python
    @property
    def rotation(self) -> np.array:
        try:
            rotation = self.node["pose"]["rotation"]
            q = Quaternion([e.value() for e in rotation])
        except Exception: # <-- here
            q = Quaternion()
        return q.elements
```

I am not sure what is the most correct way to handle this though. But at least doing this for me lets me work on the point cloud. 

Are there are any easy ways to amend such a .e57 file with a "corrupt" scanheader?

**Comment by Ephraim-Bryski** [comment]
I agree with @Napam in that I don't think it's correct to check for a `KeyError`. Even though the error's coming from the invalid "rotation" key, under the hood, there's a custom `__getitem__` method. I think this in turn is accessing the C++ get method, which looks for the path:

```cpp
cls_StructureNode.def("get", (Node (StructureNode::*)(const std::string &) const) &StructureNode::get, "pathName"_a);
```

Since the path is undefined, it's raises a libe57 error.

To be a bit more precise, although basically what @Napam proposed, I think this modification works:

```python
@property
def rotation(self) -> np.array:
    try:
        rotation = self.node["pose"]["rotation"]
        q = Quaternion([e.value() for e in rotation])
    except libe57.E57Exception:
        q = Quaternion()
    return q.elements
```

Another approach that wouldn't rely on exceptions would be to do something similar to `has_pose` but check whether it has rotation instead:

```python
def has_rotation(self):
    if not self.node.isDefined("pose"):
        return False # immediately exit so it doesn't crash when trying to get "pose"
    return self.node["pose"].isDefined("rotation")
 ```
which would then be used:

```python
@property
def rotation(self) -> np.array:
    if self.has_rotation():
        rotation = self.node["pose"]["rotation"]
        q = Quaternion([e.value() for e in rotation])
    else:
        q = Quaternion()
    return q.elements
```

I like the second option more, but I think it's just personal preference.


I'm not sure if it's possible to have an e57 with a pose but not a translation (like the Trimble e57 had a pose but not a rotation), but if it is, I think it would crash on the `translation` method:

```python
@property
def translation(self):
    return np.array([e.value() for e in self.node["pose"]["translation"]])
```

If this is a concern, I think it could be fixed the same way:

```python
@property
def translation(self):
    try:
        return np.array([e.value() for e in self.node["pose"]["translation"]])
    except libe57.E57Exception:
        return np.array([0,0,0])
```

Maybe it's still nice to have the check, but if the checks are done for `translation` and `rotation`, the `has_pose` check shouldn't be needed.

```python
if header.has_pose(): # no longer needed if rotation and translation are both checked
    xyz = self.to_global(xyz, header.rotation, header.translation)
```
